# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class Contract(BaseModel):
    native_id: typing.Optional[str] = None
    title: typing.Optional[str] = None
    rules_text: typing.Optional[str] = None
    settlement_source: typing.Optional[str] = None
    resolves_at_ms: typing.Optional[int] = None

class EquivalenceVerdict(BaseModel):
    equivalent: typing.Optional[bool] = Field(default=None, description='True ONLY if the two contracts resolve identically in every possible outcome.')
    outcome_polarity: typing.Optional[types.OutcomePolarity] = None
    reason: typing.Optional[str] = Field(default=None, description='One or two sentences: the decisive match, or the specific mismatch/ambiguity.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
