# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class OutcomePolarity(str, Enum):
    DIRECT = "DIRECT"
    INVERTED = "INVERTED"

# #########################################################################
# Generated classes (4)
# #########################################################################

class Contract(BaseModel):
    native_id: str
    title: str
    rules_text: typing.Optional[str] = None
    settlement_source: typing.Optional[str] = None
    resolves_at_ms: typing.Optional[int] = None

class ContractCriteria(BaseModel):
    proposition: str = Field(description='The precise event/threshold judged, e.g. \'CPI YoY > 3.0%\'.')
    settlement_source: str = Field(description='The authority/dataset/index/exchange/station that determines the outcome.')
    timing_cutoff: str = Field(description='Exact observation time, release date, or settlement window incl. time zone; whether revisions count.')
    edge_case_rules: str = Field(description='Postponement, cancellation, ties, early resolution, scheduled-vs-actual, void/refund rules.')

class DimensionMatch(BaseModel):
    proposition: bool
    settlement_source: bool
    timing_cutoff: bool
    edge_case_rules: bool

class EquivalenceVerdict(BaseModel):
    contract_a_criteria: "ContractCriteria"
    contract_b_criteria: "ContractCriteria"
    dimension_match: "DimensionMatch"
    equivalent: bool = Field(description='True ONLY if every dimension_match field is true.')
    outcome_polarity: OutcomePolarity
    rationale: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
