# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Contract": types.Contract,
    "stream_types.Contract": stream_types.Contract,

    "types.ContractCriteria": types.ContractCriteria,
    "stream_types.ContractCriteria": stream_types.ContractCriteria,

    "types.DimensionMatch": types.DimensionMatch,
    "stream_types.DimensionMatch": stream_types.DimensionMatch,

    "types.EquivalenceVerdict": types.EquivalenceVerdict,
    "stream_types.EquivalenceVerdict": stream_types.EquivalenceVerdict,


    "types.OutcomePolarity": types.OutcomePolarity,

}